apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightsearch-app-deployment
  labels:
    app: flightsearch-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flightsearch-app
  template:
    metadata:
      labels:
        app: flightsearch-app
    spec:
      containers:
        - name: flightsearch-app
          image: docker.io/oliverjochum/flightsearch-app:0.0.1
          ports:
          - containerPort: 5100