resources:
- ./resources/flightsearch-app-deployment.yaml
- ./resources/flightsearch-app-np-svc.yaml
- ./resources/flightsearch-app-svc.yaml

namespace: dev

images:
- name: docker.io/oliverjochum/flightsearch-app
  newName: oliverjochum/flightsearch-app
  newTag: "17295873392.1"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
